
import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

// Create output directories
const outputDir = path.resolve(process.cwd(), 'build/standalone');
const assetsDir = path.resolve(outputDir, 'assets');

// Ensure directories exist
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

if (!fs.existsSync(assetsDir)) {
  fs.mkdirSync(assetsDir, { recursive: true });
}

// Function to copy directory recursively
const copyDir = (src: string, dest: string) => {
  if (!fs.existsSync(dest)) {
    fs.mkdirSync(dest, { recursive: true });
  }
  
  const entries = fs.readdirSync(src, { withFileTypes: true });
  
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    
    if (entry.isDirectory()) {
      copyDir(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
};

// Copy images and assets
console.log('Copying assets...');
const uploadsDir = path.resolve(process.cwd(), 'public/lovable-uploads');
const targetUploadsDir = path.resolve(assetsDir, 'images');

if (fs.existsSync(uploadsDir)) {
  if (!fs.existsSync(targetUploadsDir)) {
    fs.mkdirSync(targetUploadsDir, { recursive: true });
  }
  copyDir(uploadsDir, targetUploadsDir);
}

// Create standalone HTML file
console.log('Generating HTML...');
const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Mindset Coaching mit Martina | Persönliche Entwicklung & Transformation</title>
  <link rel="icon" href="./assets/images/abb0bc70-ae8b-43ce-867f-d7beece5a8a2.png" type="image/png">
  <meta name="description" content="Entdecken Sie transformatives Mindset Coaching mit Martina Domeniconi. Entwickeln Sie ein positives Mindset, erreichen Sie Ihre Ziele und leben Sie ein erfülltes Leben. Persönliche Online-Coachings in Zürich." />
  <meta name="keywords" content="Mindset Coaching, Persönlichkeitsentwicklung, Life Coach Zürich, Online Coaching, Selbstentwicklung, Transformationscoaching, Martina Domeniconi, Positives Mindset, Lebensveränderung, Coaching Schweiz" />
  <meta name="author" content="Martina Domeniconi" />

  <meta property="og:title" content="Mindset Coaching mit Martina | Persönliche Entwicklung & Transformation" />
  <meta property="og:description" content="Mindset Coaching für ein glückliches und erfülltes Leben. Entdecken Sie Ihr volles Potenzial mit professionellem Coaching." />
  <meta property="og:type" content="website" />
  <meta property="og:image" content="./assets/images/eff14ab3-8502-4ea4-9c20-75fe9b485119.png" />

  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:site" content="@martinadomeniconi" />
  <meta name="twitter:image" content="./assets/images/eff14ab3-8502-4ea4-9c20-75fe9b485119.png" />
  
  <link rel="stylesheet" href="./styles.css">
</head>
<body>
  <div id="root">
    <!-- Content will be generated by the build process -->
  </div>
  <script src="./scripts.js"></script>
</body>
</html>`;

fs.writeFileSync(path.resolve(outputDir, 'index.html'), htmlContent);

// Generate styles.css placeholder
console.log('Generating CSS...');
const cssContent = `/* Generated styles */
:root {
  --color-forest: #41773a;
  --color-moss: #85ab7e;
  --color-sage: #9bbd96;
  --color-mint: #d6ebd3;
  --color-petrol: #316d6d;
  --color-beige: #f4f1ea;
  --color-highlight: #f0f7f0;
  --color-foreground: #333333;
  --color-background: #ffffff;
}

/* Base styles */
body {
  font-family: 'Raleway', sans-serif;
  color: var(--color-foreground);
  margin: 0;
  padding: 0;
  background-color: var(--color-background);
}

/* Generated from React components */
/* This will be populated with all the converted styles */
`;

fs.writeFileSync(path.resolve(outputDir, 'styles.css'), cssContent);

// Generate scripts.js placeholder
console.log('Generating JS...');
const jsContent = `// Generated scripts
document.addEventListener('DOMContentLoaded', function() {
  // Initialize components and behaviors
  console.log('Standalone website loaded');
  
  // Script content will be populated here
});
`;

fs.writeFileSync(path.resolve(outputDir, 'scripts.js'), jsContent);

// Create a README file with instructions
const readmeContent = `# Standalone Website

This folder contains a standalone version of the website with plain HTML, CSS, and JavaScript.

## Files
- index.html: The main HTML file
- styles.css: All styles for the website
- scripts.js: JavaScript functionality
- assets/: Contains all images and other static assets

## How to use
Simply upload all these files to any web server, and the website will work without any build process.
`;

fs.writeFileSync(path.resolve(outputDir, 'README.md'), readmeContent);

console.log('✅ Standalone build completed successfully!');
console.log(`Standalone files are available in: ${outputDir}`);
